const db = require("./database");

db.exec("DELETE FROM jobs");
db.exec("DELETE FROM sqlite_sequence WHERE name='jobs'");

const jobs = [
  {
    title: "Desenvolvedor Frontend React",
    company: "TechBrasil",
    location: "São Paulo - SP",
    salary_min: 4000,
    salary_max: 7000,
    type: "CLT",
    level: "junior",
    description: "Desenvolvimento de interfaces web com React e TypeScript",
    requirements: "React, TypeScript, HTML, CSS, Git",
    status: "active",
  },
  {
    title: "Analista de QA Pleno",
    company: "QualitySoft",
    location: "Rio de Janeiro - RJ",
    salary_min: 5000,
    salary_max: 8000,
    type: "CLT",
    level: "pleno",
    description: "Testes manuais e automatizados de aplicações web e mobile",
    requirements: "Postman, Selenium, Cypress, SQL básico",
    status: "active",
  },
  {
    title: "Desenvolvedor Backend Node.js",
    company: "StartupXYZ",
    location: "Remoto",
    salary_min: 6000,
    salary_max: 10000,
    type: "PJ",
    level: "pleno",
    description: "Desenvolvimento de APIs REST com Node.js e bancos relacionais",
    requirements: "Node.js, Express, PostgreSQL, Docker",
    status: "active",
  },
  {
    title: "DevOps Engineer",
    company: "CloudTech",
    location: "Belo Horizonte - MG",
    salary_min: 8000,
    salary_max: 14000,
    type: "CLT",
    level: "senior",
    description: "Gerenciamento de infraestrutura cloud e pipelines CI/CD",
    requirements: "AWS, Docker, Kubernetes, Terraform, Jenkins",
    status: "active",
  },
  {
    title: "Analista de Dados",
    company: "DataInsights",
    location: "São Paulo - SP",
    salary_min: 5500,
    salary_max: 9000,
    type: "CLT",
    level: "pleno",
    description: "Análise de dados e criação de dashboards",
    requirements: "Python, SQL, Power BI, Excel avançado",
    status: "active",
  },
  {
    title: "UX/UI Designer",
    company: "DesignHub",
    location: "Curitiba - PR",
    salary_min: 4500,
    salary_max: 7500,
    type: "PJ",
    level: "junior",
    description: "Design de interfaces e experiência do usuário",
    requirements: "Figma, Adobe XD, pesquisa de usuário",
    status: "active",
  },
  {
    title: "Engenheiro de Machine Learning",
    company: "AI Solutions",
    location: "Remoto",
    salary_min: 12000,
    salary_max: 20000,
    type: "PJ",
    level: "senior",
    description: "Desenvolvimento de modelos de machine learning para produção",
    requirements: "Python, TensorFlow, PyTorch, MLOps, Docker",
    status: "active",
  },
  {
    title: "Desenvolvedor Mobile Flutter",
    company: "AppMaster",
    location: "Florianópolis - SC",
    salary_min: 5000,
    salary_max: 9000,
    type: "CLT",
    level: "pleno",
    description: "Desenvolvimento de aplicativos mobile multiplataforma com Flutter",
    requirements: "Flutter, Dart, Firebase, REST APIs",
    status: "active",
  },
  {
    title: "Scrum Master",
    company: "AgileWorks",
    location: "Porto Alegre - RS",
    salary_min: 7000,
    salary_max: 11000,
    type: "CLT",
    level: "senior",
    description: "Facilitação de cerimônias ágeis e remoção de impedimentos",
    requirements: "Certificação CSM, Jira, Confluence, Kanban",
    status: "active",
  },
  {
    title: "DBA PostgreSQL",
    company: "DataGuard",
    location: "Brasília - DF",
    salary_min: 8000,
    salary_max: 13000,
    type: "CLT",
    level: "senior",
    description: "Administração e otimização de bancos de dados PostgreSQL",
    requirements: "PostgreSQL, backup/restore, tuning, replicação",
    status: "active",
  },
  {
    title: "Estagiário de Desenvolvimento",
    company: "TechBrasil",
    location: "São Paulo - SP",
    salary_min: 1500,
    salary_max: 2000,
    type: "Estágio",
    level: "estagio",
    description: "Apoio no desenvolvimento de features e correção de bugs",
    requirements: "Cursando Ciência da Computação ou similar, lógica de programação",
    status: "active",
  },
  {
    title: "Tech Lead Full Stack",
    company: "MegaCorp",
    location: "São Paulo - SP",
    salary_min: 15000,
    salary_max: 22000,
    type: "CLT",
    level: "senior",
    description: "Liderança técnica de equipe full stack",
    requirements: "React, Node.js, AWS, liderança de equipe, arquitetura",
    status: "inactive",
  },
  {
    title: "Analista de Segurança da Informação",
    company: "SecureNet",
    location: "Remoto",
    salary_min: 9000,
    salary_max: 15000,
    type: "PJ",
    level: "senior",
    description: "Análise de vulnerabilidades e implementação de políticas de segurança",
    requirements: "Pentest, OWASP, firewalls, SIEM, ISO 27001",
    status: "active",
  },
  {
    title: "Desenvolvedor PHP Laravel",
    company: "WebFactory",
    location: "Goiânia - GO",
    salary_min: 3500,
    salary_max: 6000,
    type: "CLT",
    level: "junior",
    description: "Manutenção e desenvolvimento de sistemas web com Laravel",
    requirements: "PHP, Laravel, MySQL, HTML/CSS, JavaScript",
    status: "active",
  },
  {
    title: "Product Owner",
    company: "AgileWorks",
    location: "Porto Alegre - RS",
    salary_min: 8000,
    salary_max: 13000,
    type: "CLT",
    level: "pleno",
    description: "Gestão de backlog e priorização de features do produto",
    requirements: "Experiência com produtos digitais, Jira, métricas de produto",
    status: "active",
  },
  {
    title: "Desenvolvedor Java Spring Boot",
    company: "FinTechPay",
    location: "São Paulo - SP",
    salary_min: 7000,
    salary_max: 12000,
    type: "CLT",
    level: "pleno",
    description: "Desenvolvimento de microserviços para sistema financeiro",
    requirements: "Java, Spring Boot, Kafka, PostgreSQL, Docker",
    status: "active",
  },
  {
    title: "Analista de Suporte N2",
    company: "HelpDesk Pro",
    location: "Campinas - SP",
    salary_min: 3000,
    salary_max: 4500,
    type: "CLT",
    level: "junior",
    description: "Suporte técnico nível 2 para sistemas internos",
    requirements: "Windows Server, Active Directory, redes, ITIL",
    status: "inactive",
  },
  {
    title: "Arquiteto de Software",
    company: "MegaCorp",
    location: "Remoto",
    salary_min: 18000,
    salary_max: 28000,
    type: "PJ",
    level: "senior",
    description: "Definição de arquitetura e padrões técnicos da empresa",
    requirements: "Microserviços, cloud, design patterns, DDD, liderança técnica",
    status: "active",
  },
  {
    title: "QA Automation Engineer",
    company: "QualitySoft",
    location: "Remoto",
    salary_min: 7000,
    salary_max: 12000,
    type: "PJ",
    level: "pleno",
    description: "Automação de testes end-to-end e integração contínua",
    requirements: "Cypress, Playwright, JavaScript, CI/CD, Docker",
    status: "active",
  },
  {
    title: "Desenvolvedor Python Django",
    company: "DataInsights",
    location: "São Paulo - SP",
    salary_min: 5000,
    salary_max: 8500,
    type: "CLT",
    level: "junior",
    description: "Desenvolvimento de aplicações web com Django e Django REST",
    requirements: "Python, Django, PostgreSQL, REST APIs, Git",
    status: "active",
  },
];

const insert = db.prepare(`
  INSERT INTO jobs (title, company, location, salary_min, salary_max, type, level, description, requirements, status)
  VALUES (@title, @company, @location, @salary_min, @salary_max, @type, @level, @description, @requirements, @status)
`);

const insertMany = db.transaction((jobs) => {
  for (const job of jobs) {
    insert.run(job);
  }
});

insertMany(jobs);

console.log(`✅ ${jobs.length} vagas inseridas com sucesso!`);
process.exit(0);
